### ISSUE TITLE
tez-ui compilation failed

### ISSUE THREAD

**Issue by taabich** [TOSIT-IO/tez-old#1]
Hi,
Tez-ui is failed, the component bower try download https://github.com/Teleborder/FileSaver.js.git but this js is not available on github.

To resolve the problem:

Edit  tez-ui/src/main/webapp/ember-cli-build.js 
Replace app.import('bower_components/file-saver.js/FileSaver.js'); 
by app.import('bower_components/file-saver/FileSaver.js'); 

Edit  tez-ui/src/main/webapp/bower.js 
Replace "file-saver.js": "1.20150507.2", 
by "file-saver": "v1.2.0" 

On tez-ui/src/main/webapp/bower-shrinkwrap.json 
 replace
-  "https://github.com/Teleborder/FileSaver.js.git": { 
    "1.20150507.2": "b7cf622909258086bc63ad764d08fcaed780ab42" 
  }, 
By
  "https://github.com/eligrey/FileSaver.js.git": { 
    "1.2.0": "a6d11998e279e94f2926b2a897231355dfab48ab" 
  }, 

Best regards

**Comment by rpignolet** [comment]
`tez-ui` is not used for TDP deployment, we will disable it to avoid build errors, see #2.

**Comment by rpignolet** [comment]
I'm closing this issue, we do not build `tez-ui` anymore, see my previous comment.
